# Generated by Django 5.0.7 on 2024-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='profile_pic'),
        ),
    ]
